---
dependency:
  name: galaxy
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  enabled: false
platforms:
  - name: testaddsudoers
    box: ubuntu/xenial64
provisioner:
  name: ansible
  options:
    vvv: True
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
